### ISSUE TITLE
New version does not work

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/terminal_debloater#29]
After update to new version this modules stopped working.
Running "debloat" in terminal shows the message that su should be runned first.
Running with root permissions shows "module is not installed".
The module is present in Magisk list.
Reinstall does not help.
In the same time the previous version works.

The same is true for Systemizer also.

**Comment by veez21** [comment]
What magisk version are you running? This requires Magisk v19

**Comment by gjf** [comment]
v19 is not released yet. If you desgined the latest module for beta - it would be good to put a test into installation script and to install a proper version depending on what Magisk is on the system.

**Comment by veez21** [comment]
I'll do an update for it to be compatible with previous versions.
